# Generated by Django 6.1 on 2026-08-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_feedback_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coffee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.coffee')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pages.order')),
            ],
        ),
    ]
